### ISSUE TITLE
Make final filename on disk configurable

### ISSUE THREAD

**Issue by JamesHenry** [dominhhai/koa-busboy#1]
Thanks for the lib @dominhhai! I have had to fork it just to work around the fact that the actual filename that gets written to disk on the server is opaquely modified:

https://github.com/dominhhai/koa-busboy/blob/master/extract.js#L16

It would be ideal if this was configurable - in my particular use case my filenames are already guaranteed to be unique and I don't really want to have to parse the `fileReadStream.path` to work out what the final filename is on disk. I also find it unintuitive that `fileReadStream.filename` shows the original filename and not the final, modified one.

**Comment by dominhhai** [comment]
Thanks for your suggestion!

1. Final filename configuration
   Awesome idea. However, it isn't easy for handling multi-upload files.
Anw, configuring the rule for making final filename is not hard, IMO.  

2.  fileReadStream.filename
    This will shown the original filename (uploaded file), because sometime we need this value for other checking or validation. And, the final filename (on disk) can be gotten from file ReadStream, so,  we don't need to save the final filename with `fileReadStream.filename`.

**Comment by dominhhai** [comment]
@JamesHenry 
Are you OK with new feature?

**Comment by JamesHenry** [comment]
That's great, thanks a lot!
